/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *cinr;
  GtkWidget *label_cinr;
  GtkWidget *button_rechercher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label18;
  GtkWidget *button_modifier1;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label21;
  GtkWidget *button_supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label16;
  GtkWidget *button_ajout;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *lniveau;
  GtkWidget *lage;
  GtkWidget *lprenom;
  GtkWidget *lnom;
  GtkWidget *lmdp;
  GtkWidget *l9;
  GtkWidget *label_nom;
  GtkWidget *label_prenom;
  GtkWidget *label_niveau;
  GtkWidget *label_age;
  GtkWidget *label_mdp;
  GtkWidget *label_education;
  GtkWidget *leducation;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("fenetre_afficher"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 24, 248);
  gtk_widget_set_size_request (treeview1, 696, 176);

  cinr = gtk_entry_new ();
  gtk_widget_show (cinr);
  gtk_fixed_put (GTK_FIXED (fixed1), cinr, 144, 24);
  gtk_widget_set_size_request (cinr, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinr), 8226);

  label_cinr = gtk_label_new (_("CIN :"));
  gtk_widget_show (label_cinr);
  gtk_fixed_put (GTK_FIXED (fixed1), label_cinr, 96, 24);
  gtk_widget_set_size_request (label_cinr, 49, 25);

  button_rechercher = gtk_button_new ();
  gtk_widget_show (button_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed1), button_rechercher, 312, 24);
  gtk_widget_set_size_request (button_rechercher, 112, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_rechercher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  button_modifier1 = gtk_button_new ();
  gtk_widget_show (button_modifier1);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modifier1, 72, 176);
  gtk_widget_set_size_request (button_modifier1, 112, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_modifier1), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox9), label21, FALSE, FALSE, 0);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supprimer, 216, 176);
  gtk_widget_set_size_request (button_supprimer, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox4), label16, FALSE, FALSE, 0);

  button_ajout = gtk_button_new ();
  gtk_widget_show (button_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajout, 344, 176);
  gtk_widget_set_size_request (button_ajout, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajout), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  lniveau = gtk_label_new ("");
  gtk_widget_show (lniveau);
  gtk_fixed_put (GTK_FIXED (fixed1), lniveau, 448, 80);
  gtk_widget_set_size_request (lniveau, 96, 16);

  lage = gtk_label_new ("");
  gtk_widget_show (lage);
  gtk_fixed_put (GTK_FIXED (fixed1), lage, 600, 80);
  gtk_widget_set_size_request (lage, 88, 17);

  lprenom = gtk_label_new ("");
  gtk_widget_show (lprenom);
  gtk_fixed_put (GTK_FIXED (fixed1), lprenom, 272, 81);
  gtk_widget_set_size_request (lprenom, 104, 16);

  lnom = gtk_label_new ("");
  gtk_widget_show (lnom);
  gtk_fixed_put (GTK_FIXED (fixed1), lnom, 72, 80);
  gtk_widget_set_size_request (lnom, 88, 17);

  lmdp = gtk_label_new ("");
  gtk_widget_show (lmdp);
  gtk_fixed_put (GTK_FIXED (fixed1), lmdp, 136, 128);
  gtk_widget_set_size_request (lmdp, 104, 17);

  l9 = gtk_label_new ("");
  gtk_widget_show (l9);
  gtk_fixed_put (GTK_FIXED (fixed1), l9, 456, 32);
  gtk_widget_set_size_request (l9, 49, 17);

  label_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_nom, 16, 80);
  gtk_widget_set_size_request (label_nom, 49, 17);
  GTK_WIDGET_SET_FLAGS (label_nom, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (label_nom), TRUE);

  label_prenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), label_prenom, 176, 80);
  gtk_widget_set_size_request (label_prenom, 88, 17);

  label_niveau = gtk_label_new (_("Niveau :"));
  gtk_widget_show (label_niveau);
  gtk_fixed_put (GTK_FIXED (fixed1), label_niveau, 384, 80);
  gtk_widget_set_size_request (label_niveau, 49, 17);

  label_age = gtk_label_new (_("Age :"));
  gtk_widget_show (label_age);
  gtk_fixed_put (GTK_FIXED (fixed1), label_age, 544, 80);
  gtk_widget_set_size_request (label_age, 49, 17);

  label_mdp = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label_mdp);
  gtk_fixed_put (GTK_FIXED (fixed1), label_mdp, 8, 128);
  gtk_widget_set_size_request (label_mdp, 121, 16);

  label_education = gtk_label_new (_("Education"));
  gtk_widget_show (label_education);
  gtk_fixed_put (GTK_FIXED (fixed1), label_education, 280, 120);
  gtk_widget_set_size_request (label_education, 88, 24);

  leducation = gtk_label_new ("");
  gtk_widget_show (leducation);
  gtk_fixed_put (GTK_FIXED (fixed1), leducation, 392, 128);
  gtk_widget_set_size_request (leducation, 49, 17);

  g_signal_connect ((gpointer) button_rechercher, "clicked",
                    G_CALLBACK (on_button_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier1, "clicked",
                    G_CALLBACK (on_button_modifier1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajout, "clicked",
                    G_CALLBACK (on_button_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, cinr, "cinr");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_cinr, "label_cinr");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_rechercher, "button_rechercher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label18, "label18");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_modifier1, "button_modifier1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image9, "image9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label21, "label21");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label16, "label16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, button_ajout, "button_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, lniveau, "lniveau");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, lage, "lage");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, lprenom, "lprenom");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, lnom, "lnom");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, lmdp, "lmdp");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, l9, "l9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_prenom, "label_prenom");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_niveau, "label_niveau");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_age, "label_age");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_mdp, "label_mdp");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label_education, "label_education");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, leducation, "leducation");

  return fenetre_afficher;
}

GtkWidget*
create_fenetre_ajouter (void)
{
  GtkWidget *fenetre_ajouter;
  GtkWidget *fixed2;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_age;
  GtkWidget *label_prenom;
  GtkWidget *entry_cin;
  GtkWidget *entry_mdp;
  GtkWidget *label_nom;
  GtkWidget *label_age;
  GtkWidget *label_cin;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkObject *spinbutton_jour_adj;
  GtkWidget *spinbutton_jour;
  GtkWidget *label_mdp;
  GtkWidget *button_ajouter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *button_afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label15;
  GtkWidget *button_modifiier;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label19;
  GtkWidget *label22;
  GtkWidget *radiobutton_mr;
  GSList *radiobutton_mr_group = NULL;
  GtkWidget *label8;
  GtkWidget *radiobutton_mme;
  GtkWidget *label13;
  GtkWidget *checkbutton_ing;
  GtkWidget *checkbutton_business;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *checkbutton_prepa;
  GtkWidget *niveau;
  GtkWidget *label;
  GtkWidget *combobox2;
  GtkWidget *combobox1;

  fenetre_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajouter), _("fenetre_ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_ajouter), fixed2);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nom, 144, 88);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_prenom, 464, 80);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_age = gtk_entry_new ();
  gtk_widget_show (entry_age);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_age, 144, 160);
  gtk_widget_set_size_request (entry_age, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_age), 8226);

  label_prenom = gtk_label_new (_("Prenom "));
  gtk_widget_show (label_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), label_prenom, 344, 80);
  gtk_widget_set_size_request (label_prenom, 88, 24);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_cin, 144, 240);
  gtk_widget_set_size_request (entry_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry_mdp = gtk_entry_new ();
  gtk_widget_show (entry_mdp);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mdp, 472, 248);
  gtk_widget_set_size_request (entry_mdp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp), 8226);

  label_nom = gtk_label_new (_("Nom "));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), label_nom, 64, 88);
  gtk_widget_set_size_request (label_nom, 41, 17);

  label_age = gtk_label_new (_("Age"));
  gtk_widget_show (label_age);
  gtk_fixed_put (GTK_FIXED (fixed2), label_age, 72, 168);
  gtk_widget_set_size_request (label_age, 41, 17);

  label_cin = gtk_label_new (_("CIN"));
  gtk_widget_show (label_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), label_cin, 72, 248);
  gtk_widget_set_size_request (label_cin, 41, 17);

  spinbutton_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mois, 352, 456);
  gtk_widget_set_size_request (spinbutton_mois, 60, 27);

  spinbutton_annee_adj = gtk_adjustment_new (1990, 1990, 2020, 1, 10, 10);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_annee, 496, 456);
  gtk_widget_set_size_request (spinbutton_annee, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_annee), TRUE);

  spinbutton_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_adj), 1, 2);
  gtk_widget_show (spinbutton_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_jour, 216, 456);
  gtk_widget_set_size_request (spinbutton_jour, 60, 27);

  label_mdp = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label_mdp);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mdp, 336, 248);
  gtk_widget_set_size_request (label_mdp, 128, 25);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter, 48, 512);
  gtk_widget_set_size_request (button_ajouter, 104, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);

  button_afficher = gtk_button_new ();
  gtk_widget_show (button_afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), button_afficher, 176, 512);
  gtk_widget_set_size_request (button_afficher, 112, 29);
  gtk_button_set_focus_on_click (GTK_BUTTON (button_afficher), FALSE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);

  button_modifiier = gtk_button_new ();
  gtk_widget_show (button_modifiier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifiier, 312, 512);
  gtk_widget_set_size_request (button_modifiier, 106, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_modifiier), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox7), label19, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Formulaire d'ajout d'un nouvel \303\251tudiant "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 184, 24);
  gtk_widget_set_size_request (label22, 376, 25);

  radiobutton_mr = gtk_radio_button_new_with_mnemonic (NULL, _("Mr"));
  gtk_widget_show (radiobutton_mr);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_mr, 464, 312);
  gtk_widget_set_size_request (radiobutton_mr, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mr), radiobutton_mr_group);
  radiobutton_mr_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mr));

  label8 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 48, 304);
  gtk_widget_set_size_request (label8, 40, 25);

  radiobutton_mme = gtk_radio_button_new_with_mnemonic (NULL, _("Mme"));
  gtk_widget_show (radiobutton_mme);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton_mme, 136, 304);
  gtk_widget_set_size_request (radiobutton_mme, 124, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mme), radiobutton_mr_group);
  radiobutton_mr_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mme));

  label13 = gtk_label_new (_("Education"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 24, 360);
  gtk_widget_set_size_request (label13, 104, 24);

  checkbutton_ing = gtk_check_button_new_with_mnemonic (_("Cycle d'ingenieur"));
  gtk_widget_show (checkbutton_ing);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_ing, 136, 360);
  gtk_widget_set_size_request (checkbutton_ing, 118, 24);

  checkbutton_business = gtk_check_button_new_with_mnemonic (_("Business"));
  gtk_widget_show (checkbutton_business);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_business, 464, 360);
  gtk_widget_set_size_request (checkbutton_business, 118, 24);

  label11 = gtk_label_new (_("Jour"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 160, 456);
  gtk_widget_set_size_request (label11, 48, 24);

  label12 = gtk_label_new (_("La date d'entr\303\251e"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 8, 456);
  gtk_widget_set_size_request (label12, 144, 24);

  label9 = gtk_label_new (_("mois"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 296, 456);
  gtk_widget_set_size_request (label9, 40, 24);

  label10 = gtk_label_new (_("annee"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 432, 456);
  gtk_widget_set_size_request (label10, 48, 24);

  checkbutton_prepa = gtk_check_button_new_with_mnemonic (_("Prepa"));
  gtk_widget_show (checkbutton_prepa);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton_prepa, 320, 360);
  gtk_widget_set_size_request (checkbutton_prepa, 118, 24);

  niveau = gtk_label_new_with_mnemonic (_("Niveau"));
  gtk_widget_show (niveau);
  gtk_fixed_put (GTK_FIXED (fixed2), niveau, 40, 408);
  gtk_widget_set_size_request (niveau, 72, 25);

  label = gtk_label_new (_("Bloc "));
  gtk_widget_show (label);
  gtk_fixed_put (GTK_FIXED (fixed2), label, 384, 408);
  gtk_widget_set_size_request (label, 57, 25);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox2, 136, 408);
  gtk_widget_set_size_request (combobox2, 128, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1\303\250re ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2\303\250me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3\303\250me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4\303\250me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("5\303\250me ann\303\251e"));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 456, 408);
  gtk_widget_set_size_request (combobox1, 128, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("A1==>A10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("B1==>B10"));

  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifiier, "clicked",
                    G_CALLBACK (on_button_modifiier_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_ing, "toggled",
                    G_CALLBACK (on_checkbutton_ing_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_business, "toggled",
                    G_CALLBACK (on_checkbutton_business_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_prepa, "toggled",
                    G_CALLBACK (on_checkbutton_prepa_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajouter, fenetre_ajouter, "fenetre_ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, entry_age, "entry_age");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label_prenom, "label_prenom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, entry_mdp, "entry_mdp");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label_age, "label_age");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label_cin, "label_cin");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, spinbutton_jour, "spinbutton_jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label_mdp, "label_mdp");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, button_afficher, "button_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label15, "label15");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, button_modifiier, "button_modifiier");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label19, "label19");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label22, "label22");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, radiobutton_mr, "radiobutton_mr");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, radiobutton_mme, "radiobutton_mme");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label13, "label13");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, checkbutton_ing, "checkbutton_ing");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, checkbutton_business, "checkbutton_business");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label12, "label12");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, checkbutton_prepa, "checkbutton_prepa");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, niveau, "niveau");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, label, "label");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajouter, combobox1, "combobox1");

  return fenetre_ajouter;
}

